### ISSUE TITLE
python activate.py error

### ISSUE THREAD

**Issue by neezee** [kinecosystem/kin-sdk-python#67]
**CentOS 7  python3**

When I run python3 activate.py XXX ...

**The following is the exception information:**
Traceback (most recent call last):
  File "activate.py", line 16, in <module>
    Main()
  File "activate.py", line 11, in main
    Builder.sign()
  File "/root/.local/lib/python3.7/site-packages/kin/stellar/builder.py", line 69, in sign
    Self.sequence = self.get_sequence()
  File "/root/.local/lib/python3.7/site-packages/kin/stellar/builder.py", line 54, in get_sequence
    Return self.horizon.account(self.address).get('sequence')
  File "/root/.local/lib/python3.7/site-packages/kin/stellar/horizon.py", line 124, in account
    Return self.query(url)
  File "/root/.local/lib/python3.7/site-packages/kin/stellar/horizon.py", line 120, in query
    Return check_horizon_reply(reply) if not sse else reply
  File "/root/.local/lib/python3.7/site-packages/kin/stellar/horizon.py", line 244, in check_horizon_reply
    Raise HorizonError(reply)
kin.stellar.errors.HorizonError: _data='{'type': 'not_found', 'title': 'Resource Missing', 'status': 404, 'detail': 'The resource at the url requested was not found. This is usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided.', 'instance': None, 'extras': None}'

**Comment by neezee** [comment]
Sorry, wrong project:   https://github.com/kinecosystem/kin-devplatform-wallet-creation/issues/3
